version: '3'
services:
  traefik:
    image: traefik:v1.4-alpine
    command: --web --docker
    ports:
      - "80:80"
      - "8083:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - frontend
      - backend
  frontend:
    image: ir2sora/present-constructor-frontend:1.3.0
    depends_on:
      - backend
    labels:
      - "traefik.backend=frontend"
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.port=80"
  backend:
    image: ir2sora/present-constructor-backend:1.3.0-SNAPSHOT
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    ports:
      - "8080:8080"
    volumes:
      - ${DB_DATA_PATH}:/var/lib/h2/data
    labels:
      - "traefik.backend=backend"
      - "traefik.frontend.rule=PathPrefix:/api/,/oauth/"
      - "traefik.port=8080"