version: '3'
services:
  traefik:
    image: traefik:v1.4-alpine
    command: --web --docker
    ports:
      - "80:80"
      - "8083:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - frontend
      - backend
  frontend:
    image: ir2sora/present-constructor-frontend:1.4.1
    depends_on:
      - backend
    labels:
      - "traefik.backend=frontend"
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.port=80"
  backend:
    image: ir2sora/present-constructor-backend:1.4.1
    depends_on:
      - backend_mysql
    links:
      - "backend_mysql:mysql"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    ports:
      - "8080:8080"
    labels:
      - "traefik.backend=backend"
      - "traefik.frontend.rule=PathPrefix:/api/,/oauth/"
      - "traefik.port=8080"
  backend_mysql:
      image: mysql:5.7.21
      environment:
        - MYSQL_USER=${DB_USER}
        - MYSQL_PASSWORD=${DB_PASS}
      ports:
        - "3307:3306"
      volumes:
        - ${DB_DATA_PATH}:/var/lib/mysql