version: 2
jobs:
  build_backend:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/present-constructor/backend

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/present-constructor
      - restore_cache:
          keys:
          - present-constructor-backend-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: present-constructor-backend-{{ checksum "pom.xml" }}

      - run: mvn integration-test

  build_frontend:
    docker:
      - image: circleci/node:8.9.1-browsers

    working_directory: ~/present-constructor/frontend

    steps:
      - checkout:
          path: ~/present-constructor

      - restore_cache:
          key: present-constructor-frontend-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          key: present-constructor-frontend-{{ checksum "package.json" }}
          paths:
            - "node_modules"

      - run: npm run build -- --prod

workflows:
  version: 2
  build:
    jobs:
      - build_backend
      - build_frontend