defaults: &backend
  docker:
    - image: circleci/openjdk:8-jdk
  working_directory: ~/present-constructor/backend
  environment:
    MAVEN_OPTS: -Xmx3200m

defaults: &frontend
  docker:
    - image: circleci/node:8.9.1-browsers
  working_directory: ~/present-constructor/frontend

version: 2
jobs:
  build_backend:
    <<: *backend

    steps:
      - checkout:
          path: ~/present-constructor
      - restore_cache:
          key: present-constructor-backend-{{ checksum "build.gradle" }}

      - run: ./gradlew test -i

      - save_cache:
          paths:
            - ~/.gradle
          key: present-constructor-backend-{{ checksum "build.gradle" }}

      - persist_to_workspace:
          root: ~/present-constructor/backend
          paths:
            - ./*

  build_backend_docker:
    <<: *backend

    steps:
      - setup_remote_docker

      - attach_workspace:
          at: ~/present-constructor/backend

      - restore_cache:
          key: present-constructor-backend-{{ checksum "build.gradle" }}

      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: ./gradlew jib -i

      - save_cache:
          paths:
            - ~/.gradle
          key: present-constructor-backend-{{ checksum "build.gradle" }}

  build_frontend:
    <<: *frontend

    steps:
      - checkout:
          path: ~/present-constructor

      - restore_cache:
          key: present-constructor-frontend-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          key: present-constructor-frontend-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"

      - run: yarn run build --prod

      - persist_to_workspace:
          root: ~/present-constructor/frontend
          paths:
            - ./*

  build_frontend_docker:
    <<: *frontend

    steps:
      - setup_remote_docker

      - attach_workspace:
          at: ~/present-constructor/frontend

      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: yarn run docker-build
      - run: yarn run docker-push

workflows:
  version: 2
  build:
    jobs:
      - build_backend
      - build_backend_docker:
          requires:
            - build_backend

      - build_frontend
      - build_frontend_docker:
          requires:
            - build_frontend